# Машинное обучение и анализ данных
## Математика и Python
Задание 1

In [1]:
print ('Иванов Иван Иванович'.split(' '))

['Иванов', 'Иван', 'Иванович']


In [2]:
a=5

In [3]:
print(a)

5


In [7]:
a = 'qwe'

In [8]:
print(a)

qwe


In [9]:
a = ['1',12,True]

In [10]:
print(a)

['1', 12, True]


In [11]:
print(type(a))

<class 'list'>


In [12]:
print (a[1])

12


In [13]:
b = (1,'222', 'asad')

In [14]:
print(b[1])

222


In [19]:
c = {1:2,'2':'abc',3:'qwe'}

In [21]:
c['2']

'abc'

In [23]:
import pandas as pd

In [26]:
a = pd.DataFrame()

In [27]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [40]:
import numpy
import scipy
from scipy import spatial
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [41]:
scipy.spatial.distance.cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

array([[  7.,   6.,   1.],
       [  4.,   3.,   4.],
       [  4.,   5.,  12.]])

In [43]:
scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

In [44]:
a = numpy.array([0, -1, 11])
b = numpy.array([3, 7, 2])

In [45]:
b.dot(a)

15

In [46]:
a*b

array([ 0, -7, 22])

In [48]:
numpy.dot(a,b)

15

In [49]:
a = numpy.array([8, 10, -1, 0, 0])

In [51]:
a[:, numpy.newaxis]

array([[[ 8]],

       [[10]],

       [[-1]],

       [[ 0]],

       [[ 0]]])

In [52]:
a[numpy.newaxis, :]

array([[[ 8],
        [10],
        [-1],
        [ 0],
        [ 0]]])

In [54]:
a.reshape((5, 1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 1], [1, 2]])
at = a.transpose()

In [3]:
print(a)
print(at)
print (a.dot(at))

[[1 1]
 [1 2]]
[[1 1]
 [1 2]]
[[2 3]
 [3 5]]


In [5]:
e = np.arange(1, 13, 2).reshape((3, 2))

In [6]:
print (e)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [7]:
d = np.ones((10, 10))
print(d)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [8]:
print (d[1,5])

1.0


In [9]:
b = np.eye(2, 3)
print(b)

[[ 1.  0.  0.]
 [ 0.  1.  0.]]


In [10]:
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [11]:
a = np.eye(4, 5)

In [12]:
a[[0, 3], [1, 3]]

array([ 0.,  1.])